### ISSUE TITLE
Embedding int64 broke it

### ISSUE THREAD

**Issue by freman** [alecthomas/jsonschema#31]
```
type Duration struct {
	time.Duration
}

func main() {
	jsonschema.Reflect(&Duration{})
}}}
```

```
panic: reflect: NumField of non-struct type

goroutine 1 [running]:
reflect.(*rtype).NumField(0x10f3fc0, 0x6)
	/usr/local/go/src/reflect/type.go:982 +0x5f
github.com/alecthomas/jsonschema.(*Reflector).reflectStructFields(0xc000052eed, 0xc0000e4000, 0xc0000c64b0, 0x1126e80, 0x10f3fc0)
	go/src/github.com/alecthomas/jsonschema/reflect.go:269 +0xb0
github.com/alecthomas/jsonschema.(*Reflector).reflectStructFields(0xc000052eed, 0xc0000e4000, 0xc0000c64b0, 0x1126e80, 0x10f8280)
	go/src/github.com/alecthomas/jsonschema/reflect.go:274 +0x3d8
github.com/alecthomas/jsonschema.(*Reflector).reflectStruct(0xc000052eed, 0xc0000c64b0, 0x1126e80, 0x10f8280, 0x11f99a0)
	go/src/github.com/alecthomas/jsonschema/reflect.go:257 +0x18f
github.com/alecthomas/jsonschema.(*Reflector).reflectTypeToSchema(0xc000052eed, 0xc0000c64b0, 0x1126e80, 0x10f8280, 0x11f99a0)
	go/src/github.com/alecthomas/jsonschema/reflect.go:191 +0x8a8
github.com/alecthomas/jsonschema.(*Reflector).reflectTypeToSchema(0xc000052eed, 0xc0000c64b0, 0x1126e80, 0x10f4080, 0x10f8880)
	go/src/github.com/alecthomas/jsonschema/reflect.go:241 +0x822
github.com/alecthomas/jsonschema.(*Reflector).ReflectFromType(0xc000052eed, 0x1126e80, 0x10f4080, 0x10)
	go/src/github.com/alecthomas/jsonschema/reflect.go:129 +0x2f8
github.com/alecthomas/jsonschema.ReflectFromType(...)
	go/src/github.com/alecthomas/jsonschema/reflect.go:82
github.com/alecthomas/jsonschema.Reflect(0x10f4080, 0xc0000c4230, 0x4001)
	go/src/github.com/alecthomas/jsonschema/reflect.go:76 +0x79
main.main()
	go/src/test/gonfig/main.go:141 +0xb3
exit status 2
```

**Comment by alecthomas** [comment]
This should be fixed by #35.
